"""Bird's-eye-view free space estimation from simulated lidar using an inverse sensor model."""

from __future__ import annotations

from freespace_grid.algorithm import (
    Accumulator,
    ScanUpdate,
    Traversal,
    apply_scan,
    resample_grid,
    scan_update,
    traverse_rays,
)
from freespace_grid.analysis import (
    Agreement,
    SmearReport,
    measure_smear,
    score_grid,
    threshold_sweep,
    tolerance_sweep,
)
from freespace_grid.model import (
    CellState,
    GridSpec,
    LogOddsModel,
    OccupancyGrid,
    Pose2D,
    cell_to_world,
    log_odds_to_prob,
    prob_to_log_odds,
    world_to_cell,
)
from freespace_grid.pipeline import (
    Circle,
    LidarSpec,
    MappingTrace,
    MovingCircle,
    Polygon,
    RunConfig,
    Scan,
    Scenario,
    Scene,
    dynamic_corridor,
    enclosed_room,
    run_mapping,
    simulate_scan,
    urban_block,
)

__all__ = [
    "Accumulator",
    "Agreement",
    "CellState",
    "Circle",
    "GridSpec",
    "LidarSpec",
    "LogOddsModel",
    "MappingTrace",
    "MovingCircle",
    "OccupancyGrid",
    "Polygon",
    "Pose2D",
    "RunConfig",
    "Scan",
    "ScanUpdate",
    "Scenario",
    "Scene",
    "SmearReport",
    "Traversal",
    "__version__",
    "apply_scan",
    "cell_to_world",
    "dynamic_corridor",
    "enclosed_room",
    "log_odds_to_prob",
    "measure_smear",
    "prob_to_log_odds",
    "resample_grid",
    "run_mapping",
    "scan_update",
    "score_grid",
    "simulate_scan",
    "threshold_sweep",
    "tolerance_sweep",
    "traverse_rays",
    "urban_block",
    "world_to_cell",
]

__version__ = "0.1.0"
